### ISSUE TITLE
Even after specifiying output directory, no coverage data is shown

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [shanbin/scoverage-plugin#13] opened 2016-05-03 13:45 UTC
I specify `servision/target/scoverage-report` as the scoverage report directory and `scoverage.xml` as the scoverage report file.

In this directory, I can see an `index.html` that is viewable with a browser.

But the link the plugin creates in the Jenkins project page,shows empty content.
I think this is a bug.

Using latest version: 1.3.0 and Jenkins 1.651

**Comment by shanbin** [comment] 2016-05-03 17:23
Which build tool is being used?

**Comment by DavidPerezIngeniero** [comment] 2016-05-04 07:08
Of course SBT and scoverage-plugin version 1.3.0.

**Comment by shanbin** [comment] 2016-08-03 21:30
Should be a duplicate of #15

**Closed by shanbin** 2016-08-03 21:30 UTC
